services:
  - type: web
    name: flask-backend
    env: python
    runtime: python-3.11.6
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dshackathon2025
          property: connectionString
